services:
  - type: web
    name: virtual-book-library
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:5000 server.app:app"
    repo: https://github.com/levi-s2/Virtual-book-Library
    branch: main
    autoDeploy: true
