"""added rating

Revision ID: 7ca2d7605bc9
Revises: 04689d0e9ac2
Create Date: 2024-06-06 18:01:51.947270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca2d7605bc9'
down_revision = '04689d0e9ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_books', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_books', 'rating')
    # ### end Alembic commands ###
